version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XDEBUG_ENABLED=1 # Imposta a 1 per abilitare XDebug
    command: >
      sh -c "if [ \"$XDEBUG_ENABLED\" = \"1\" ]; then
               mv /usr/local/etc/php/conf.d/xdebug.ini.disabled /usr/local/etc/php/conf.d/xdebug.ini;
             fi &&
             apache2-foreground"
