version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
